# uncomment the line below to test local
# local_backend: true
backend:
  # uncomment the line below to test local, and not to save the change
  # name: test-repo
  name: git-gateway
  branch: develop
publish_mode: editorial_workflow
media_folder: "datasets"
collections:
  - name: "dataset"
    label: "Dataset"
    folder: "datasets"
    editor:
      preview: false
    create: true
    extension: "mdx"
    format: "frontmatter"
    title: fields.id
    identifier_field: fields.id
    slug: "{{fields.id}}.data"
    preview_path: "{{fields.thematics[0]}}/datasets/{{fields.id}}/explore"
    summary: "{{fields.name}}"
    fields:
      - label: "Featured on"
        name: "featuredOn"
        widget: "relation"
        required: false
        collection: thematic
        value_field: id
        search_fields:
          - id
          - name
        multiple: true
      - label: Usage
        name: usage
        widget: list
        required: false
        fields:
          - label: "url"
            name: "url"
            widget: string
            required: false
          - label: "Label"
            name: "label"
            widget: string
            required: false
          - label: "Title"
            name: "title"
            widget: string
            required: false
      - {
          label: "Dataset ID",
          name: "id",
          hint: "ID for dataset",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Thematics"
        name: "thematics"
        widget: "relation"
        required: false
        collection: thematic
        value_field: id
        multiple: true
        search_fields:
          - id
          - name
      - label: "Image"
        name: "media"
        required: false
        widget: "object"
        fields:
          - { label: "File", name: "src", required: false, widget: "image" }
          - {
              label: "Alt text",
              name: "alt",
              required: false,
              widget: "string",
            }
          - label: "Author"
            name: "author"
            widget: "object"
            required: false
            fields:
              - {
                  label: "Name",
                  name: "name",
                  widget: "string",
                  required: false,
                }
              - { label: "URL", name: "url", widget: "string", required: false }
      - label: "Layers"
        name: layers
        widget: list
        fields:
          - { label: "Layer ID", name: "id", widget: "string" }
          - label: STAC ID
            name: stacCol
            widget: select-async
            # widget options:
            url: https://staging-stac.delta-backend.com/collections
            data_path: collections
            value_field: id
            display_field: id
          - label: "Layer Name"
            name: "name"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "type"
            name: type
            widget: "string"
            default: "raster"
          - label: "Initial datetime"
            name: initialDatetime
            widget: "select"
            required: false
            options: ["oldest", "newest"]
          - label: "Zoom Extent"
            hint: "minZoom(int), maxZoom(int) ex. 3, 17"
            name: zoomExtent
            required: false
            widget: number_list
          - label: Layer to compare
            name: compare
            widget: object
            required: false
            fields:
              - label: Dataset ID
                name: datasetId
                required: false
                widget: string
              - label: Layer ID
                name: layerId
                required: false
                widget: string
          - label: "Source parameter"
            name: sourceParams
            widget: object
            required: false
            fields:
              - label: rescale
                name: rescale
                hint: lowestValue, highestValue ex. 0, 150000000
                widget: number_list
                required: false
              - label: bidx
                name: bidx
                widget: string
                required: false
              - label: color formula
                name: color_formula
                widget: string
                required: false
              - label: colormap
                name: colormap
                widget: string
                required: false
              - label: colormap name
                name: colormap_name
                widget: select
                options:
                  [
                    "accent",
                    "accent_r",
                    "afmhot",
                    "afmhot_r",
                    "autumn",
                    "autumn_r",
                    "binary",
                    "binary_r",
                    "blues",
                    "blues_r",
                    "bone",
                    "bone_r",
                    "brbg",
                    "brbg_r",
                    "brg",
                    "brg_r",
                    "bugn",
                    "bugn_r",
                    "bupu",
                    "bupu_r",
                    "bwr",
                    "bwr_r",
                    "cfastie",
                    "cividis",
                    "cividis_r",
                    "cmrmap",
                    "cmrmap_r",
                    "cool",
                    "cool_r",
                    "coolwarm",
                    "coolwarm_r",
                    "copper",
                    "copper_r",
                    "cubehelix",
                    "cubehelix_r",
                    "dark2",
                    "dark2_r",
                    "flag",
                    "flag_r",
                    "gist_earth",
                    "gist_earth_r",
                    "gist_gray",
                    "gist_gray_r",
                    "gist_heat",
                    "gist_heat_r",
                    "gist_ncar",
                    "gist_ncar_r",
                    "gist_rainbow",
                    "gist_rainbow_r",
                    "gist_stern",
                    "gist_stern_r",
                    "gist_yarg",
                    "gist_yarg_r",
                    "gnbu",
                    "gnbu_r",
                    "gnuplot",
                    "gnuplot2",
                    "gnuplot2_r",
                    "gnuplot_r",
                    "gray",
                    "gray_r",
                    "greens",
                    "greens_r",
                    "greys",
                    "greys_r",
                    "hot",
                    "hot_r",
                    "hsv",
                    "hsv_r",
                    "inferno",
                    "inferno_r",
                    "jet",
                    "jet_r",
                    "magma",
                    "magma_r",
                    "nipy_spectral",
                    "nipy_spectral_r",
                    "ocean",
                    "ocean_r",
                    "oranges",
                    "oranges_r",
                    "orrd",
                    "orrd_r",
                    "paired",
                    "paired_r",
                    "pastel1",
                    "pastel1_r",
                    "pastel2",
                    "pastel2_r",
                    "pink",
                    "pink_r",
                    "piyg",
                    "piyg_r",
                    "plasma",
                    "plasma_r",
                    "prgn",
                    "prgn_r",
                    "prism",
                    "prism_r",
                    "pubu",
                    "pubu_r",
                    "pubugn",
                    "pubugn_r",
                    "puor",
                    "puor_r",
                    "purd",
                    "purd_r",
                    "purples",
                    "purples_r",
                    "rainbow",
                    "rainbow_r",
                    "rdbu",
                    "rdbu_r",
                    "rdgy",
                    "rdgy_r",
                    "rdpu",
                    "rdpu_r",
                    "rdylbu",
                    "rdylbu_r",
                    "rdylgn",
                    "rdylgn_r",
                    "reds",
                    "reds_r",
                    "rplumbo",
                    "schwarzwald",
                    "seismic",
                    "seismic_r",
                    "set1",
                    "set1_r",
                    "set2",
                    "set2_r",
                    "set3",
                    "set3_r",
                    "spectral",
                    "spectral_r",
                    "spring",
                    "spring_r",
                    "summer",
                    "summer_r",
                    "tab10",
                    "tab10_r",
                    "tab20",
                    "tab20_r",
                    "tab20b",
                    "tab20b_r",
                    "tab20c",
                    "tab20c_r",
                    "terrain",
                    "terrain_r",
                    "twilight",
                    "twilight_r",
                    "twilight_shifted",
                    "twilight_shifted_r",
                    "viridis",
                    "viridis_r",
                    "winter",
                    "winter_r",
                    "wistia",
                    "wistia_r",
                    "ylgn",
                    "ylgn_r",
                    "ylgnbu",
                    "ylgnbu_r",
                    "ylorbr",
                    "ylorbr_r",
                    "ylorrd",
                    "ylorrd_r",
                  ]
                required: false
          - label: "Legend"
            name: "legend"
            widget: "object"
            required: false
            fields:
              - label: "Type"
                name: "type"
                widget: "string"
                required: false
                default: "gradient"
              - label: "Min value label"
                name: min
                required: false
                widget: string
              - label: "Max value label"
                name: max
                required: false
                widget: string
              - label: "Stops for Gradient"
                name: "stops"
                hint: "ex. #ff0000, #91bfdb, #e0f3f8, ..."
                required: false
                widget: list
          - label: Projection
            name: projection
            widget: object
            required: false
            fields:
              - {
                  label: "ID",
                  name: "id",
                  widget: "select",
                  options:
                    [
                      "albers",
                      "equalEarth",
                      "equirectangular",
                      "lambertConformalConic",
                      "mercator",
                      "naturalEarth",
                      "winkelTripel",
                      "globe",
                      "polarNorth",
                      "polarSouth",
                    ],
                  required: false,
                }
              - {
                  label: "Center (float, float)",
                  name: "center",
                  widget: "number_list",
                  required: false,
                }
              - {
                  label: "Parallels (float, float)",
                  name: "parallels",
                  widget: "number_list",
                  required: false,
                }
        # - label: "Stops for Category"
        #   name: "stops"
        #   widget: "list"
        #   fields:
        #     - {label: "color", name: "", widget: "text" }
        #     - {label: "label", name: "label", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "thematic"
    label: "Thematic"
    folder: "thematic"
    media_folder: "thematic"
    create: true
    extension: "mdx"
    format: "frontmatter"
    title: fields.id
    identifier_field: fields.id
    slug: "{{fields.id}}.thematic"
    summary: "{{fields.name}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Thematic name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "About"
        name: "about"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
      - label: "Image"
        name: "media"
        widget: "object"
        fields:
          - { label: "File", name: "src", widget: "image" }
          - { label: "Alt text", name: "alt", widget: "string" }
          - label: "Author"
            name: "author"
            widget: "object"
            required: false
            fields:
              - {
                  label: "Name",
                  name: "name",
                  required: false,
                  widget: "string",
                }
              - { label: "URL", name: "url", required: false, widget: "string" }
